spring:
  application:
    name: spring-system-clinica-veterinaria
  datasource:
    url: jdbc:mysql://localhost:3306/veterinaria
    username: root
    password: MyMagolorDS
    name: system-vet-clinica
  datasource:
    url: jdbc:mysql://localhost:3306/bd_clinic_animal
    username: root
    password: Indra24go
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        format_sql: true

