spring:
  application:
    name: system-vet-clinica
  datasource:
    url: jdbc:mysql://localhost:3306/Bd_clinicaAni
    username: root
    password: Indra24go
    name: system-vet-clinica
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


