spring:
  application:
    name: system-vet-clinica
  datasource:
    url: jdbc:mysql://localhost:3306/Bd_clinicaAni
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


